[Run]
start_urls = ["https://www.romsmode.com/roms/"]
allowed_domains = ['romsmode.com']
categories = [
    'acorn-8-bit',
    'acorn-archimedes',
    'acorn-electron',
    'amiga-500',
    'amstrad-cpc',
    'amstrad-gx4000',
    'apple-i',
    'apple-ii',
    'apple-ii-gs',
    'atari-2600',
    'atari-5200',
    'atari-7800',
    'atari-800',
    'atari-jaguar',
    'atari-lynx',
    'atari-st',
    'bally-pro-arcade-astrocade',
    'bbc-micro',
    'camputers-lynx',
    'capcom-play-system-1',
    'capcom-play-system-2',
    'casio-loopy',
    'casio-pv1000',
    'colecovision',
    'colecovision-adam',
    'commodore-64',
    'commodore-max-machine',
    'commodore-pet',
    'commodore-plus4-c16',
    'commodore-vic20',
    'dragon-data-dragon',
    'elektronika-bk',
    'emerson-arcadia-2001',
    'entex-adventure-vision',
    'epoch-super-cassette-vision',
    'fairchild-channel-f',
    'funtech-super-acan',
    'galaksija',
    'game-gear',
    'gameboy',
    'gameboy-advance',
    'gameboy-color',
    'gamecube',
    'gamepark-gp32',
    'gce-vectrex',
    'hartung-game-master',
    'intellivision',
    'interact-family-computer',
    'kaypro-ii',
    'luxor-abc-800',
    'magnavox-odyssey-2',
    'mame',
    'mattel-aquarius',
    'memotech-mtx512',
    'miles-gordon-sam-coupe',
    'msx-2',
    'msx-computer',
    'neo-geo',
    'neo-geo-pocket',
    'nintendo',
    'nintendo-3ds',
    'nintendo-64',
    'nintendo-ds',
    'nintendo-famicom-disk-system',
    'nintendo-pokemon-mini',
    'nintendo-virtual-boy',
    'nintendo-wii',
    'nokia-n-gage',
    'pel-varazdin-orao',
    'philips-videopac',
    'playstation',
    'playstation-2',
    'playstation-portable',
    'rca-studio-ii',
    'robotron-z1013',
    'sega-32x',
    'dreamcast',
    'sega-genesis',
    'sega-master-system',
    'sega-pico',
    'sega-sg1000',
    'sega-super-control-station',
    'sega-visual-memory-system',
    'sharp-mz-700',
    'sharp-x68000',
    'sinclair-zx81',
    'sufami-turbo',
    'super-grafx',
    'super-nintendo',
    'tandy-color-computer',
    'tangerine-oric',
    'thomson-mo5',
    'tiger-game-com',
    'turbografx-16',
    'vtech-creativision',
    'vtech-v-smile',
    'wang-vs',
    'watara-supervision',
    'wonderswan',
    'microsoft-xbox',
    'z-machine-infocom',
    'zx-spectrum'
]
allowed_regex = [
    '^https://www.romsgames.net/roms/acorn-8-bit',
    '^https://www.romsgames.net/roms/acorn-archimedes',
    '^https://www.romsgames.net/roms/acorn-electron',
    '^https://www.romsgames.net/roms/amiga-500',
    '^https://www.romsgames.net/roms/amstrad-cpc',
    '^https://www.romsgames.net/roms/amstrad-gx4000',
    '^https://www.romsgames.net/roms/apple-i',
    '^https://www.romsgames.net/roms/apple-ii',
    '^https://www.romsgames.net/roms/apple-ii-gs',
    '^https://www.romsgames.net/roms/atari-2600',
    '^https://www.romsgames.net/roms/atari-5200',
    '^https://www.romsgames.net/roms/atari-7800',
    '^https://www.romsgames.net/roms/atari-800',
    '^https://www.romsgames.net/roms/atari-jaguar',
    '^https://www.romsgames.net/roms/atari-lynx',
    '^https://www.romsgames.net/roms/atari-st',
    '^https://www.romsgames.net/roms/bally-pro-arcade-astrocade',
    '^https://www.romsgames.net/roms/bbc-micro',
    '^https://www.romsgames.net/roms/camputers-lynx',
    '^https://www.romsgames.net/roms/capcom-play-system-1',
    '^https://www.romsgames.net/roms/capcom-play-system-2',
    '^https://www.romsgames.net/roms/casio-loopy',
    '^https://www.romsgames.net/roms/casio-pv1000',
    '^https://www.romsgames.net/roms/colecovision',
    '^https://www.romsgames.net/roms/colecovision-adam',
    '^https://www.romsgames.net/roms/commodore-64',
    '^https://www.romsgames.net/roms/commodore-max-machine',
    '^https://www.romsgames.net/roms/commodore-pet',
    '^https://www.romsgames.net/roms/commodore-plus4-c16',
    '^https://www.romsgames.net/roms/commodore-vic20',
    '^https://www.romsgames.net/roms/dragon-data-dragon',
    '^https://www.romsgames.net/roms/elektronika-bk',
    '^https://www.romsgames.net/roms/emerson-arcadia-2001',
    '^https://www.romsgames.net/roms/entex-adventure-vision',
    '^https://www.romsgames.net/roms/epoch-super-cassette-vision',
    '^https://www.romsgames.net/roms/fairchild-channel-f',
    '^https://www.romsgames.net/roms/funtech-super-acan',
    '^https://www.romsgames.net/roms/galaksija',
    '^https://www.romsgames.net/roms/game-gear',
    '^https://www.romsgames.net/roms/gameboy',
    '^https://www.romsgames.net/roms/gameboy-advance',
    '^https://www.romsgames.net/roms/gameboy-color',
    '^https://www.romsgames.net/roms/gamecube',
    '^https://www.romsgames.net/roms/gamepark-gp32',
    '^https://www.romsgames.net/roms/gce-vectrex',
    '^https://www.romsgames.net/roms/hartung-game-master',
    '^https://www.romsgames.net/roms/intellivision',
    '^https://www.romsgames.net/roms/interact-family-computer',
    '^https://www.romsgames.net/roms/kaypro-ii',
    '^https://www.romsgames.net/roms/luxor-abc-800',
    '^https://www.romsgames.net/roms/magnavox-odyssey-2',
    '^https://www.romsgames.net/roms/mame',
    '^https://www.romsgames.net/roms/mattel-aquarius',
    '^https://www.romsgames.net/roms/memotech-mtx512',
    '^https://www.romsgames.net/roms/miles-gordon-sam-coupe',
    '^https://www.romsgames.net/roms/msx-2',
    '^https://www.romsgames.net/roms/msx-computer',
    '^https://www.romsgames.net/roms/neo-geo',
    '^https://www.romsgames.net/roms/neo-geo-pocket',
    '^https://www.romsgames.net/roms/nintendo',
    '^https://www.romsgames.net/roms/nintendo-3ds',
    '^https://www.romsgames.net/roms/nintendo-64',
    '^https://www.romsgames.net/roms/nintendo-ds',
    '^https://www.romsgames.net/roms/nintendo-famicom-disk-system',
    '^https://www.romsgames.net/roms/nintendo-pokemon-mini',
    '^https://www.romsgames.net/roms/nintendo-virtual-boy',
    '^https://www.romsgames.net/roms/nintendo-wii',
    '^https://www.romsgames.net/roms/nokia-n-gage',
    '^https://www.romsgames.net/roms/pel-varazdin-orao',
    '^https://www.romsgames.net/roms/philips-videopac',
    '^https://www.romsgames.net/roms/playstation',
    '^https://www.romsgames.net/roms/playstation-2',
    '^https://www.romsgames.net/roms/playstation-portable',
    '^https://www.romsgames.net/roms/rca-studio-ii',
    '^https://www.romsgames.net/roms/robotron-z1013',
    '^https://www.romsgames.net/roms/sega-32x',
    '^https://www.romsgames.net/roms/dreamcast',
    '^https://www.romsgames.net/roms/sega-genesis',
    '^https://www.romsgames.net/roms/sega-master-system',
    '^https://www.romsgames.net/roms/sega-pico',
    '^https://www.romsgames.net/roms/sega-sg1000',
    '^https://www.romsgames.net/roms/sega-super-control-station',
    '^https://www.romsgames.net/roms/sega-visual-memory-system',
    '^https://www.romsgames.net/roms/sharp-mz-700',
    '^https://www.romsgames.net/roms/sharp-x68000',
    '^https://www.romsgames.net/roms/sinclair-zx81',
    '^https://www.romsgames.net/roms/sufami-turbo',
    '^https://www.romsgames.net/roms/super-grafx',
    '^https://www.romsgames.net/roms/super-nintendo',
    '^https://www.romsgames.net/roms/tandy-color-computer',
    '^https://www.romsgames.net/roms/tangerine-oric',
    '^https://www.romsgames.net/roms/thomson-mo5',
    '^https://www.romsgames.net/roms/tiger-game-com',
    '^https://www.romsgames.net/roms/turbografx-16',
    '^https://www.romsgames.net/roms/vtech-creativision',
    '^https://www.romsgames.net/roms/vtech-v-smile',
    '^https://www.romsgames.net/roms/wang-vs',
    '^https://www.romsgames.net/roms/watara-supervision',
    '^https://www.romsgames.net/roms/wonderswan',
    '^https://www.romsgames.net/roms/microsoft-xbox',
    '^https://www.romsgames.net/roms/z-machine-infocom',
    '^https://www.romsgames.net/roms/zx-spectrum'
]
denied_extensions = ['jpg', 'png', 'pdf', 'jpeg']
rm_none = true

[Xpath]
title = "//h1[contains(@class, \"is-fz-34\")]/text()"
image = "//div[contains(@class, \"product__img-box\")]//img/@src"
region = "//span[contains(@class, \"ico-flag\")]/@title"
download_link = "//div[contains(@class, \"wait\")]//a[contains(@class, \"wait__link\")]/@href"
